#!/bin/bash

if [ $# -eq 1 ] && [ "$1" = "manifest" ]; then
    sunbeam query -n '{
        title: "Bitwarden Vault",
        commands: [
            {
                name: "list-passwords",
                title: "List Passwords",
                mode: "view"
            }
        ]
    }'
    exit 0
fi

# check for dependencies
if ! command -v bkt &> /dev/null; then
    echo "bkt could not be found"
    exit 1
fi

if ! command -v bw &> /dev/null; then
    echo "bw could not be found"
    exit 1
fi

COMMAND=$(sunbeam query -r '.command')
if [ "$COMMAND" = "list-passwords" ]; then
    bkt --ttl 24h --stale 1h -- bw --nointeraction list items --session "$BW_SESSION" | sunbeam query '.[] | {
        title: .name,
        subtitle: (.login.username // ""),
        actions: [
            {
                title: "Copy Password",
                onAction: {
                    type: "copy",
                    text: (.login.password // ""),
                    exit: true
                }
            },
            {
                title: "Copy Username",
                key: "l",
                onAction: {
                    type: "copy",
                    text: (.login.username // ""),
                    exit: true
                }
            }
        ]
    }' | sunbeam query -s '{type: "list", items: .}'
fi
